#!/bin/bash

REPORT="reports/health_report.txt"
SUMMARY="reports/ai_summary.txt"

if [ ! -f "$REPORT" ]; then
    echo "ERROR: Health report not found."
    exit 1
fi

CPU=$(grep -i "CPU" "$REPORT" | head -1)
MEMORY=$(grep -i "Memory" "$REPORT" | head -1)
DISK=$(grep -i "Disk" "$REPORT" | head -1)

{
echo "======================================"
echo "      AI HEALTH MONITOR SUMMARY"
echo "======================================"
echo ""
echo "INPUT REPORT ANALYSIS"
echo "---------------------"
echo "$CPU"
echo "$MEMORY"
echo "$DISK"
echo ""
echo "DETECTED CONDITIONS"
echo "-------------------"

if echo "$MEMORY" | grep -qE '[89][0-9]%'; then
    echo "WARNING: High memory usage detected."
else
    echo "Memory usage: NORMAL"
fi

if echo "$DISK" | grep -qE '[89][0-9]%'; then
    echo "WARNING: High disk usage detected."
else
    echo "Disk usage: NORMAL"
fi

echo ""
echo "ACTIONABLE RECOMMENDATIONS"
echo "--------------------------"
echo "1. Monitor CPU and memory periodically."
echo "2. Investigate processes consuming excessive resources."
echo "3. Clean unnecessary files if disk usage becomes high."
echo ""
echo "OVERALL RESULT"
echo "--------------"
echo "Automated health analysis completed."
echo ""
echo "Generated by Prompt-Based Automation"
echo "======================================"
} > "$SUMMARY"

echo "AI summary generated successfully."
