name: Linux Health Monitor CI/CD

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 9 * * *"

  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  health-monitor:

    runs-on: ubuntu-latest

    steps:

      # Step 1: Download the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Give execute permission to scripts
      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh
          chmod +x tests/*.sh

      # Step 3: Create directories required by the scripts
      - name: Create required directories
        run: |
          mkdir -p reports
          mkdir -p logs

      # Step 4: Run Linux health monitoring
      - name: Run health monitor
        run: |
          ./scripts/health_monitor.sh

      # Step 5: Run automated tests
      - name: Run automated tests
        run: |
          ./tests/test_health_monitor.sh

      - name: Update Agile Project - Done
        if: success()
        env:
          GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        run: |
          gh api graphql -f query='
          mutation {
            updateProjectV2ItemFieldValue(
              input: {
                projectId: "PVT_kwHOElnf_M4BhfnL"
                itemId: "PVTI_lAHOElnf_M4BhfnLzg4DISs"
                fieldId: "PVTSSF_lAHOElnf_M4BhfnLzhgbKUs"
                value: { singleSelectOptionId: "98236657" }
              }
            ) {
              projectV2Item {
                id
              }
            }
          }'

      # Step 6: Upload generated health report
      - name: Upload health report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: health-report
          path: reports/health_report.txt
